#include "../../hajlib/include/galloisField.h"
#include "../../hajlib/include/hprintf.h"

#include "../../includes/hash/whirlpool.h"

#include "../../includes/consts/consts.h"

/*
 * Whirlpool constant generator
 * 
 * This file generates all necessary constants for the Whirlpool hash function:
 * - S-box (substitution box) - using official values from the specification
 * - Round constants RC[0..9] - generated from the S-box
 * - MDS matrix (Maximum Distance Separable) - generated as circulant matrix
 * - Initial value (IV) - all zeros
 * 
 * According to the Whirlpool specification:
 * - S-box: The official values from Table 3 of the Whirlpool document
 * - Round constants: first 80 bytes of S-box, grouped in 8-byte chunks (big-endian)
 * - MDS matrix: circulant matrix based on [0x01,0x01,0x04,0x01,0x08,0x05,0x02,0x09]
 * - IV: all zeros (standard for Whirlpool)
 */

/* Official Whirlpool S-box values from the specification (Table 3) */
static const uint8_t WHIRLPOOL_SBOX[256] = {
	0x18,0x23,0xC6,0xE8,0x87,0xB8,0x01,0x4F,0x36,0xA6,0xD2,0xF5,0x79,0x6F,0x91,0x52,
	0x60,0xBC,0x9B,0x8E,0xA3,0x0C,0x7B,0x35,0x1D,0xE0,0xD7,0xC2,0x2E,0x4B,0xFE,0x57,
	0x15,0x77,0x37,0xE5,0x9F,0xF0,0x4A,0xDA,0x58,0xC9,0x29,0x0A,0xB1,0xA0,0x6B,0x85,
	0xBD,0x5D,0x10,0xF4,0xCB,0x3E,0x05,0x67,0xE4,0x27,0x41,0x8B,0xA7,0x7D,0x95,0xD8,
	0xFB,0xEE,0x7C,0x66,0xDD,0x17,0x47,0x9E,0xCA,0x2D,0xBF,0x07,0xAD,0x5A,0x83,0x33,
	0x63,0x02,0xAA,0x71,0xC8,0x19,0x49,0xD9,0xF2,0xE3,0x5B,0x88,0x9A,0x26,0x32,0xB0,
	0xE9,0x0F,0xD5,0x80,0xBE,0xCD,0x34,0x48,0xFF,0x7A,0x90,0x5F,0x20,0x68,0x1A,0xAE,
	0xB4,0x54,0x93,0x22,0x64,0xF1,0x73,0x12,0x40,0x08,0xC3,0xEC,0xDB,0xA1,0x8D,0x3D,
	0x97,0x00,0xCF,0x2B,0x76,0x82,0xD6,0x1B,0xB5,0xAF,0x6A,0x50,0x45,0xF3,0x30,0xEF,
	0x3F,0x55,0xA2,0xEA,0x65,0xBA,0x2F,0xC0,0xDE,0x1C,0xFD,0x4D,0x92,0x75,0x06,0x8A,
	0xB2,0xE6,0x0E,0x1F,0x62,0xD4,0xA8,0x96,0xF9,0xC5,0x25,0x59,0x84,0x72,0x39,0x4C,
	0x5E,0x78,0x38,0x8C,0xD1,0xA5,0xE2,0x61,0xB3,0x21,0x9C,0x1E,0x43,0xC7,0xFC,0x04,
	0x51,0x99,0x6D,0x0D,0xFA,0xDF,0x7E,0x24,0x3B,0xAB,0xCE,0x11,0x8F,0x4E,0xB7,0xEB,
	0x3C,0x81,0x94,0xF7,0xB9,0x13,0x2C,0xD3,0xE7,0x6E,0xC4,0x03,0x56,0x44,0x7F,0xA9,
	0x2A,0xBB,0xC1,0x53,0xDC,0x0B,0x9D,0x6C,0x31,0x74,0xF6,0x46,0xAC,0x89,0x14,0xE1,
	0x16,0x3A,0x69,0x09,0x70,0xB6,0xD0,0xED,0xCC,0x42,0x98,0xA4,0x28,0x5C,0xF8,0x86
};

/**
 * Generate the circulant MDS matrix
 * 
 * The MDS matrix is circulant: each row is the previous row rotated right by 1.
 * The base vector is [0x01, 0x01, 0x04, 0x01, 0x08, 0x05, 0x02, 0x09]
 * which was chosen to provide optimal diffusion properties.
 * 
 * @param mds 8x8 output matrix to fill
 */
static void generateMdsMatrix(uint8_t mds[8][8])
{
	/* Base row of the circulant matrix */
	const uint8_t base[8] = {0x01, 0x01, 0x04, 0x01, 0x08, 0x05, 0x02, 0x09};
	
	for (int i = 0; i < 8; i++)
		for (int j = 0; j < 8; j++)
			/* Each row is the previous row shifted right by 1 */
			mds[i][j] = base[(j - i + 8) % 8];
}

/**
 * @brief Compute a single entry of the T-tables for Whirlpool
 * 
 * The T-tables combine the S-box and MDS matrix transformations for efficient round processing.
 * For each column of the MDS matrix, we compute a 64-bit value that represents the transformation of an input byte through the S-box
 * and then multiplied by the MDS coefficients.
 * 
 * @param col - column index (0..7) for the MDS matrix
 * @param x - input byte to transform (0..255)
 * @param whirlpool_MDS - The MDS matrix (8x8) to use for generating the T-tables
 * @return 64-bit value representing the combined S-box and MDS transformation for the given column
 */
static uint64_t computeTableEntry(int src_col, uint8_t x, const uint8_t whirlpool_MDS[8][8])
{
	uint8_t s = WHIRLPOOL_SBOX[x];
	uint64_t result = 0;
	/* For each row of the MDS matrix, multiply the S-box output by the corresponding coefficient 
	 * and place it in the correct byte position (big-endian order)
	 */
	for (int dst_col = 0; dst_col < 8; dst_col++) {
		uint8_t coeff = whirlpool_MDS[src_col][dst_col];
		if (coeff != 0) {
			uint8_t product = ft_gf2nMul(s, coeff, WHIRLPOOL_POLY, 8);
			result |= (uint64_t)product << (56 - 8 * dst_col); /* Place in big-endian position */
		}
	}
	return (result);
}
/**
 * Generate T-tables for Whirlpool
 * 
 * The T-tables are precomputed tables that combine the S-box and MDS matrix for efficient round transformations.
 * They are generated by applying the S-box to each byte and then multiplying by the corresponding MDS matrix coefficients.
 * This allows the round function to be implemented with fewer operations, improving performance.
 * 
 * There are 8 T-tables, one for each column of the MDS matrix. Each table has 256 entries of 64 bits (8 bytes).
 * Total size: 8 * 256 * 8 = 16KB, which fits perfectly in modern CPU caches.
 * 
 * @param fd File descriptor to write the T-tables to (must be open for writing)
 * @param whirlpool_MDS The MDS matrix to use for generating the T-tables
 */
static void generateTtables(int fd, const uint8_t whirlpool_MDS[8][8])
{
	ft_dprintf(fd, " /**\n * T-tables combine SubBytes and MixRows for each column of the MDS matrix.\n");
	ft_dprintf(fd, " * For a given column j and input byte x, T[j][x] contains the 64-bit result\n");
	ft_dprintf(fd, " * of applying the S-box to x and then multiplying by the MDS coefficients\n");
	ft_dprintf(fd, " * for that column. The result is stored in big-endian order, where byte 0\n");
	ft_dprintf(fd, " * of the 64-bit word corresponds to row 0 of the state.\n");
	ft_dprintf(fd, " *\n");
	ft_dprintf(fd, " * During a round, for each column j, we compute:\n");
	ft_dprintf(fd, " *   for each row i: temp[i] ^= T[j][state[(i-j+8)%%8] >> (56-8*j) & 0xFF]\n");
	ft_dprintf(fd, " *\n");
	ft_dprintf(fd, " * This replaces γ (SubBytes), π (ShiftColumns), and θ (MixRows) with\n");
	ft_dprintf(fd, " * simple XOR operations and table lookups, dramatically improving performance.\n");
	ft_dprintf(fd, " */\n");

	ft_dprintf(fd, "static const uint64_t g_whirlpool_T[8][256] = {\n");
	
	/* Generate each of the 8 T-tables */
	for (int col = 0; col < 8; col++) {
		ft_dprintf(fd, "\t/* Table for MDS column %d */\n", col);
		ft_dprintf(fd, "\t{\n");
		
		/* For each of the 256 possible input bytes */
		for (int x = 0; x < 256; x++) {
			/* Compute the table entry */
			uint64_t entry = computeTableEntry(col, (uint8_t)x, whirlpool_MDS);
			
			/* Format: 16 entries per line for readability */
			if (x % 4 == 0)
				ft_dprintf(fd, "\t\t");
			
			/* Print the 64-bit value in hexadecimal with proper formatting */
			ft_dprintf(fd, "0x");
			for (int i = 0; i < 8; i++) {
				uint8_t byte = (entry >> (56 - 8 * i)) & 0xFF;
				ft_dprintf(fd, "%02X", byte);
			}
			ft_dprintf(fd, "ULL");
			
			/* Add comma if not the last entry */
			if (x < 255)
				ft_dprintf(fd, ", ");
			
			/* New line every 4 entries */
			if ((x + 1) % 4 == 0)
				ft_dprintf(fd, "\n");
		}
		
		/* Close the current table */
		ft_dprintf(fd, "\t}");
		
		/* Add comma if not the last table */
		if (col < 7)
			ft_dprintf(fd, ",\n\n");
		else
			ft_dprintf(fd, "\n");
	}
	
	ft_dprintf(fd, "};\n\n");
}
/**
 * Generate Whirlpool constants header file
 * 
 * This function writes a complete C header file with all Whirlpool constants:
 * - S-box: 256 bytes (official values from the specification)
 * - Round constants: 10 x 64-bit values (big-endian, from S-box bytes 0..79)
 * - MDS matrix: 8x8 byte matrix (circulant)
 * - Initial value: 8 x 64-bit zeros
 * 
 * @param fd File descriptor to write to (must be open for writing)
 * @return 0 on success
 */
int generateWhirlpoolHeader(int fd)
{
	uint8_t	mds[8][8];	   /* MDS matrix storage */

	ft_dprintf(fd, "#include <stdint.h>\n\n");

	/*
	 * Step 1: Output the S-box using official values from the specification
	 * 
	 * The Whirlpool S-box was designed using a recursive structure with
	 * mini-boxes and a pseudo-random permutation R generated by Rijndael.
	 * The official values are provided in Table 3 of the Whirlpool document.
	 */
	ft_dprintf(fd, "/* Whirlpool S-box */\n");
	ft_dprintf(fd, "/* Official values from the Whirlpool specification (Table 3) */\n");
	ft_dprintf(fd, "/* Generated using a recursive structure with mini-boxes E, E⁻¹, and R */\n");
	ft_dprintf(fd, "static const uint8_t g_whirlpool_S[256] = {\n");

	/* Write S-box to file (8 values per line for readability) */
	for (int i = 0; i < 256; i++) {
		if (i % 8 == 0) ft_dprintf(fd, "\t");
		ft_dprintf(fd, "0x%02X", WHIRLPOOL_SBOX[i]);
		if (i < 255) ft_dprintf(fd, ",");
		ft_dprintf(fd, (i % 8 == 7) ? "\n" : " ");
	}
	ft_dprintf(fd, "};\n\n");

	/*
	 * Step 2: Generate round constants RC[0..9]
	 * 
	 * Round constants are taken directly from the S-box:
	 * - RC[r] = S[8*r] || S[8*r+1] || ... || S[8*r+7] (concatenation)
	 * - Stored in big-endian order (most significant byte first)
	 * - This uses the first 80 bytes of the S-box (indices 0..79)
	 * 
	 * These constants are XORed with the state in each round
	 * to break symmetry and provide round-dependent randomness.
	 */
	ft_dprintf(fd, "/* Whirlpool round constants RC[0..9] (64-bit, big-endian) */\n");
	ft_dprintf(fd, "/* Generated from first 80 bytes of S-box (indices 0..79) */\n");
	ft_dprintf(fd, "/* Each constant: S[8*r] << 56 | S[8*r+1] << 48 | ... | S[8*r+7] */\n");

	ft_dprintf(fd, "static const uint64_t g_whirlpool_RC[10] = {\n");
	
	for (int r = 0; r < 10; r++) {
		
		uint64_t rc = 0;
		
		for (int j = 0; j < 8; j++) {
			int idx = 8 * r + j;
			uint64_t s_val = WHIRLPOOL_SBOX[idx];
			int shift = 56 - 8 * j;
			uint64_t contribution = s_val << shift;
			rc |= contribution;
		}

		ft_dprintf(fd, "\t0x");
		for (int i = 0; i < 8; i++) {
			uint8_t byte = (rc >> (56 - 8 * i)) & 0xFF;
			ft_dprintf(fd, "%02X", byte);
		}
		ft_dprintf(fd, "ULL%s\n", (r == 9) ? "" : ",");
	}

	ft_dprintf(fd, "};\n\n");

	/*
	 * Step 3: Generate MDS matrix
	 * 
	 * The MDS matrix provides optimal diffusion in the linear transformation.
	 * It is circulant, meaning each row is a cyclic shift of the base row.
	 * The base row was chosen to have maximum branch number (9) in GF(2^8).
	 */
	generateMdsMatrix(mds);
	
	ft_dprintf(fd, "/* Whirlpool MDS matrix (8×8) */\n");
	ft_dprintf(fd, "/* Circulant matrix with base row [0x01,0x01,0x04,0x01,0x08,0x05,0x02,0x09] */\n");
	ft_dprintf(fd, "/* Provides optimal diffusion (branch number 9) */\n");
	ft_dprintf(fd, "static const uint8_t g_whirlpool_MDS[8][8] = {\n");
	
	/* Write matrix row by row */
	for (int i = 0; i < 8; i++) {
		ft_dprintf(fd, "\t{");
		for (int j = 0; j < 8; j++) {
			ft_dprintf(fd, "0x%02X", mds[i][j]);
			if (j < 7) ft_dprintf(fd, ", ");
		}
		ft_dprintf(fd, "}%s\n", (i == 7) ? "" : ",");
	}
	ft_dprintf(fd, "};\n\n");

	/*
	 * Step 4: Initial hash value (IV)
	 * 
	 * Whirlpool starts with an initial state of all zeros.
	 * This is standard for most hash functions (like SHA-256 uses
	 * specific non-zero values, but Whirlpool uses zeros).
	 */
	ft_dprintf(fd, "/* Whirlpool initial hash value (IV) */\n");
	ft_dprintf(fd, "/* All zeros (standard for Whirlpool) */\n");
	ft_dprintf(fd, "static const uint64_t g_whirlpool_IV[8] = {\n");
	for (int i = 0; i < 8; i++)
		ft_dprintf(fd, "\t0x0000000000000000ULL%s\n", (i == 7) ? "" : ",");
	ft_dprintf(fd, "};\n\n");

	generateTtables(fd, mds);

	return (0);
}
