#include "../../../includes/cipher/aes.h"


#if defined(AES_USE_AESNI)
#include <immintrin.h>
#include <wmmintrin.h>

/*  ---------- Round primitives - single block ---------- */

/* Middle round: SubBytes + ShiftRows + MixColumns + AddRoundKey */
#define RE(d, rk, r)  (d) = _mm_aesenc_si128((d), (rk)[r])
#define RD(d, rk, r)  (d) = _mm_aesdec_si128((d), (rk)[r])

/* Final round: SubBytes + ShiftRows + AddRoundKey (no MixColumns) */
#define FE(d, rk, nr) (d) = _mm_aesenclast_si128((d), (rk)[nr])
#define FD(d, rk, nr) (d) = _mm_aesdeclast_si128((d), (rk)[nr])

/* Initial AddRoundKey whitening - must be done explicitly before first aesenc/aesdec.
 * Unlike ARM NEON (where vaeseq_u8 XORs the key at the start of each round),
 * AES-NI XORs the key at the END of each round, so the initial whitening
 * with rk[0] must be performed manually before entering the round loop. */
#define W1(d, rk) \
	(d) = _mm_xor_si128((d), (rk)[0])

#define W8(rk) \
	d0 = _mm_xor_si128(d0, (rk)[0]); \
	d1 = _mm_xor_si128(d1, (rk)[0]); \
	d2 = _mm_xor_si128(d2, (rk)[0]); \
	d3 = _mm_xor_si128(d3, (rk)[0]); \
	d4 = _mm_xor_si128(d4, (rk)[0]); \
	d5 = _mm_xor_si128(d5, (rk)[0]); \
	d6 = _mm_xor_si128(d6, (rk)[0]); \
	d7 = _mm_xor_si128(d7, (rk)[0])

static inline __m128i	loadRoundKey(const uint32_t *round_key)
{
	uint8_t	bytes[16];
	int		i;

	i = 0;
	while (i < 4)
	{
		bytes[i * 4 + 0] = (uint8_t)(round_key[i] >> 24);
		bytes[i * 4 + 1] = (uint8_t)(round_key[i] >> 16);
		bytes[i * 4 + 2] = (uint8_t)(round_key[i] >> 8);
		bytes[i * 4 + 3] = (uint8_t)(round_key[i]);
		i++;
	}
	return (_mm_loadu_si128((const __m128i *)bytes));
}

/**
 * @brief Prepare round keys for AES-NI instructions.
 *
 * AES-NI expects round keys in normal order (not reversed like ARM).
 * For decryption, the middle round keys need to be transformed with
 * _mm_aesimc_si128 (Inverse MixColumns).
 *
 * @param rk Output array of round keys (size: AES_MAX_ROUNDS + 1)
 * @param roundKeys Input round keys as generated by the key expansion
 * @param nr Number of rounds (10, 12, or 14)
 * @param encrypt Non-zero for encryption, zero for decryption
 */
__attribute__((target("aes"), always_inline))
static inline void	prepareKeys(__m128i			*rk,
								const uint32_t	*roundKeys,
								int				nr,
								int				encrypt)
{
	__m128i	orig[AES_MAX_ROUNDS + 1];
	int		i;

	i = 0;
	while (i <= nr)
	{
		orig[i] = loadRoundKey(&roundKeys[i * 4]);
		i++;
	}
	if (encrypt)
	{
		i = 0;
		while (i <= nr)
		{
			rk[i] = orig[i];
			i++;
		}
	}
	else
	{
		rk[0] = orig[nr];
		i = 1;
		while (i < nr)
		{
			rk[i] = _mm_aesimc_si128(orig[nr - i]);
			i++;
		}
		rk[nr] = orig[0];
	}
}

#ifdef HAJCRYPT_SMALL_FOOTPRINT

/* ---------- Small: generic 8-block function, loop not unrolled ---------- */

__attribute__((target("aes")))
static void	process8BlocksGeneric(const uint8_t		*in,
								  uint8_t			*out,
								  const __m128i		*rk,
								  int				nr,
								  int				encrypt)
{
	__m128i	d0, d1, d2, d3, d4, d5, d6, d7;
	int		r;

	/* Load 8 blocks (128 bytes) */
	d0 = _mm_loadu_si128((const __m128i *)(in +   0));
	d1 = _mm_loadu_si128((const __m128i *)(in +  AES_BLOCK_SIZE));
	d2 = _mm_loadu_si128((const __m128i *)(in +  AES_BLOCK_SIZE * 2));
	d3 = _mm_loadu_si128((const __m128i *)(in +  AES_BLOCK_SIZE * 3));
	d4 = _mm_loadu_si128((const __m128i *)(in +  AES_BLOCK_SIZE * 4));
	d5 = _mm_loadu_si128((const __m128i *)(in +  AES_BLOCK_SIZE * 5));
	d6 = _mm_loadu_si128((const __m128i *)(in +  AES_BLOCK_SIZE * 6));
	d7 = _mm_loadu_si128((const __m128i *)(in +  AES_BLOCK_SIZE * 7));

	if (encrypt)
	{
		W8(rk);
		for (r = 1; r < nr; r++)
		{
			RE(d0, rk, r); RE(d1, rk, r); RE(d2, rk, r); RE(d3, rk, r);
			RE(d4, rk, r); RE(d5, rk, r); RE(d6, rk, r); RE(d7, rk, r);
		}
		FE(d0, rk, nr); FE(d1, rk, nr); FE(d2, rk, nr); FE(d3, rk, nr);
		FE(d4, rk, nr); FE(d5, rk, nr); FE(d6, rk, nr); FE(d7, rk, nr);
	}
	else
	{
		W8(rk);
		for (r = 1; r < nr; r++)
		{
			RD(d0, rk, r); RD(d1, rk, r); RD(d2, rk, r); RD(d3, rk, r);
			RD(d4, rk, r); RD(d5, rk, r); RD(d6, rk, r); RD(d7, rk, r);
		}
		FD(d0, rk, nr); FD(d1, rk, nr); FD(d2, rk, nr); FD(d3, rk, nr);
		FD(d4, rk, nr); FD(d5, rk, nr); FD(d6, rk, nr); FD(d7, rk, nr);
	}

	/* Store 8 blocks */
	_mm_storeu_si128((__m128i *)(out +   0), d0);
	_mm_storeu_si128((__m128i *)(out +  AES_BLOCK_SIZE), d1);
	_mm_storeu_si128((__m128i *)(out +  AES_BLOCK_SIZE * 2), d2);
	_mm_storeu_si128((__m128i *)(out +  AES_BLOCK_SIZE * 3), d3);
	_mm_storeu_si128((__m128i *)(out +  AES_BLOCK_SIZE * 4), d4);
	_mm_storeu_si128((__m128i *)(out +  AES_BLOCK_SIZE * 5), d5);
	_mm_storeu_si128((__m128i *)(out +  AES_BLOCK_SIZE * 6), d6);
	_mm_storeu_si128((__m128i *)(out +  AES_BLOCK_SIZE * 7), d7);
}

__attribute__((target("aes")))
static void	processSingleBlockGeneric(__m128i		*d,
									  const __m128i	*rk,
									  int			nr,
									  int			encrypt)
{
	int	r;

	if (encrypt)
	{
		W1(*d, rk);
		for (r = 1; r < nr; r++)
			RE(*d, rk, r);
		FE(*d, rk, nr);
	}
	else
	{
		W1(*d, rk);
		for (r = 1; r < nr; r++)
			RD(*d, rk, r);
		FD(*d, rk, nr);
	}
}

__attribute__((target("aes")))
void	aesProcessBlocksX86(const uint8_t			*in,
							  uint8_t				*out,
							  const uint32_t		*roundKeys,
							  size_t				blocks,
							  int					nr,
							  int					encrypt)
{
	__m128i	rk[AES_MAX_ROUNDS + 1];
	__m128i	d;
	size_t	i;

	prepareKeys(rk, roundKeys, nr, encrypt);
	i = 0;
	while (i + 8 <= blocks)
	{
		process8BlocksGeneric(in + i * AES_BLOCK_SIZE, out + i * AES_BLOCK_SIZE, rk, nr, encrypt);
		i += 8;
	}
	while (i < blocks)
	{
		d = _mm_loadu_si128((const __m128i *)(in + i * AES_BLOCK_SIZE));
		processSingleBlockGeneric(&d, rk, nr, encrypt);
		_mm_storeu_si128((__m128i *)(out + i * AES_BLOCK_SIZE), d);
		i++;
	}
}

#else /* !HAJCRYPT_SMALL_FOOTPRINT - fully unrolled, maximum performance */

/* ---------- Round primitives - 8 blocks in parallel ---------- */

#define R8E(rk, r) \
	RE(d0, rk, r); RE(d1, rk, r); RE(d2, rk, r); RE(d3, rk, r); \
	RE(d4, rk, r); RE(d5, rk, r); RE(d6, rk, r); RE(d7, rk, r)

#define R8D(rk, r) \
	RD(d0, rk, r); RD(d1, rk, r); RD(d2, rk, r); RD(d3, rk, r); \
	RD(d4, rk, r); RD(d5, rk, r); RD(d6, rk, r); RD(d7, rk, r)

#define F8E(rk, nr) \
	FE(d0, rk, nr); FE(d1, rk, nr); FE(d2, rk, nr); FE(d3, rk, nr); \
	FE(d4, rk, nr); FE(d5, rk, nr); FE(d6, rk, nr); FE(d7, rk, nr)

#define F8D(rk, nr) \
	FD(d0, rk, nr); FD(d1, rk, nr); FD(d2, rk, nr); FD(d3, rk, nr); \
	FD(d4, rk, nr); FD(d5, rk, nr); FD(d6, rk, nr); FD(d7, rk, nr)

/* ---------- Fully unrolled round sequences per key size ---------- */

/* AES-128 : nr=10 - whitening + 9 middle rounds (1..9) + final */
#define UNROLL1_ENC_10(d, rk) \
	W1(d, rk); \
	RE(d,rk,1); RE(d,rk,2); RE(d,rk,3); RE(d,rk,4); RE(d,rk,5); \
	RE(d,rk,6); RE(d,rk,7); RE(d,rk,8); RE(d,rk,9); FE(d,rk,10)

#define UNROLL1_DEC_10(d, rk) \
	W1(d, rk); \
	RD(d,rk,1); RD(d,rk,2); RD(d,rk,3); RD(d,rk,4); RD(d,rk,5); \
	RD(d,rk,6); RD(d,rk,7); RD(d,rk,8); RD(d,rk,9); FD(d,rk,10)

#define UNROLL8_ENC_10(rk) \
	W8(rk); \
	R8E(rk,1); R8E(rk,2); R8E(rk,3); R8E(rk,4); R8E(rk,5); \
	R8E(rk,6); R8E(rk,7); R8E(rk,8); R8E(rk,9); F8E(rk,10)

#define UNROLL8_DEC_10(rk) \
	W8(rk); \
	R8D(rk,1); R8D(rk,2); R8D(rk,3); R8D(rk,4); R8D(rk,5); \
	R8D(rk,6); R8D(rk,7); R8D(rk,8); R8D(rk,9); F8D(rk,10)

/* AES-192 : nr=12 - whitening + 11 middle rounds (1..11) + final */
#define UNROLL1_ENC_12(d, rk) \
	W1(d, rk); \
	RE(d,rk,1);  RE(d,rk,2);  RE(d,rk,3);  RE(d,rk,4);  RE(d,rk,5); \
	RE(d,rk,6);  RE(d,rk,7);  RE(d,rk,8);  RE(d,rk,9);  RE(d,rk,10); \
	RE(d,rk,11); FE(d,rk,12)

#define UNROLL1_DEC_12(d, rk) \
	W1(d, rk); \
	RD(d,rk,1);  RD(d,rk,2);  RD(d,rk,3);  RD(d,rk,4);  RD(d,rk,5); \
	RD(d,rk,6);  RD(d,rk,7);  RD(d,rk,8);  RD(d,rk,9);  RD(d,rk,10); \
	RD(d,rk,11); FD(d,rk,12)

#define UNROLL8_ENC_12(rk) \
	W8(rk); \
	R8E(rk,1);  R8E(rk,2);  R8E(rk,3);  R8E(rk,4);  R8E(rk,5); \
	R8E(rk,6);  R8E(rk,7);  R8E(rk,8);  R8E(rk,9);  R8E(rk,10); \
	R8E(rk,11); F8E(rk,12)

#define UNROLL8_DEC_12(rk) \
	W8(rk); \
	R8D(rk,1);  R8D(rk,2);  R8D(rk,3);  R8D(rk,4);  R8D(rk,5); \
	R8D(rk,6);  R8D(rk,7);  R8D(rk,8);  R8D(rk,9);  R8D(rk,10); \
	R8D(rk,11); F8D(rk,12)

/* AES-256 : nr=14 - whitening + 13 middle rounds (1..13) + final */
#define UNROLL1_ENC_14(d, rk) \
	W1(d, rk); \
	RE(d,rk,1);  RE(d,rk,2);  RE(d,rk,3);  RE(d,rk,4);  RE(d,rk,5); \
	RE(d,rk,6);  RE(d,rk,7);  RE(d,rk,8);  RE(d,rk,9);  RE(d,rk,10); \
	RE(d,rk,11); RE(d,rk,12); RE(d,rk,13); FE(d,rk,14)

#define UNROLL1_DEC_14(d, rk) \
	W1(d, rk); \
	RD(d,rk,1);  RD(d,rk,2);  RD(d,rk,3);  RD(d,rk,4);  RD(d,rk,5); \
	RD(d,rk,6);  RD(d,rk,7);  RD(d,rk,8);  RD(d,rk,9);  RD(d,rk,10); \
	RD(d,rk,11); RD(d,rk,12); RD(d,rk,13); FD(d,rk,14)

#define UNROLL8_ENC_14(rk) \
	W8(rk); \
	R8E(rk,1);  R8E(rk,2);  R8E(rk,3);  R8E(rk,4);  R8E(rk,5); \
	R8E(rk,6);  R8E(rk,7);  R8E(rk,8);  R8E(rk,9);  R8E(rk,10); \
	R8E(rk,11); R8E(rk,12); R8E(rk,13); F8E(rk,14)

#define UNROLL8_DEC_14(rk) \
	W8(rk); \
	R8D(rk,1);  R8D(rk,2);  R8D(rk,3);  R8D(rk,4);  R8D(rk,5); \
	R8D(rk,6);  R8D(rk,7);  R8D(rk,8);  R8D(rk,9);  R8D(rk,10); \
	R8D(rk,11); R8D(rk,12); R8D(rk,13); F8D(rk,14)

/**
 * @brief Define AES functions for a specific key size.
 * @param NR Number of rounds
 * @param SUFFIX Suffix for function names
 */
#define DEFINE_AES_FUNCS(NR, SUFFIX) \
\
__attribute__((target("aes"), always_inline)) \
static inline void	processBlock##SUFFIX( \
	__m128i *data, const __m128i *rk, int encrypt) \
{ \
	if (encrypt) { UNROLL1_ENC_##NR(*data, rk); } \
	else         { UNROLL1_DEC_##NR(*data, rk); } \
} \
\
__attribute__((target("aes"), always_inline)) \
static inline void	process8Blocks##SUFFIX( \
	const uint8_t *in, uint8_t *out, \
	const __m128i *rk, int encrypt) \
{ \
	__m128i	d0 = _mm_loadu_si128((const __m128i *)(in +   0)); \
	__m128i	d1 = _mm_loadu_si128((const __m128i *)(in +  AES_BLOCK_SIZE)); \
	__m128i	d2 = _mm_loadu_si128((const __m128i *)(in +  AES_BLOCK_SIZE * 2)); \
	__m128i	d3 = _mm_loadu_si128((const __m128i *)(in +  AES_BLOCK_SIZE * 3)); \
	__m128i	d4 = _mm_loadu_si128((const __m128i *)(in +  AES_BLOCK_SIZE * 4)); \
	__m128i	d5 = _mm_loadu_si128((const __m128i *)(in +  AES_BLOCK_SIZE * 5)); \
	__m128i	d6 = _mm_loadu_si128((const __m128i *)(in +  AES_BLOCK_SIZE * 6)); \
	__m128i	d7 = _mm_loadu_si128((const __m128i *)(in + AES_BLOCK_SIZE * 7)); \
	if (encrypt) { UNROLL8_ENC_##NR(rk); } \
	else         { UNROLL8_DEC_##NR(rk); } \
	_mm_storeu_si128((__m128i *)(out +   0), d0); \
	_mm_storeu_si128((__m128i *)(out +  AES_BLOCK_SIZE), d1); \
	_mm_storeu_si128((__m128i *)(out +  AES_BLOCK_SIZE * 2), d2); \
	_mm_storeu_si128((__m128i *)(out +  AES_BLOCK_SIZE * 3), d3); \
	_mm_storeu_si128((__m128i *)(out +  AES_BLOCK_SIZE * 4), d4); \
	_mm_storeu_si128((__m128i *)(out +  AES_BLOCK_SIZE * 5), d5); \
	_mm_storeu_si128((__m128i *)(out +  AES_BLOCK_SIZE * 6), d6); \
	_mm_storeu_si128((__m128i *)(out +  AES_BLOCK_SIZE * 7), d7); \
}

/* Instantiate the three key-size variants */
DEFINE_AES_FUNCS(10, 128)
DEFINE_AES_FUNCS(12, 192)
DEFINE_AES_FUNCS(14, 256)

/**
 * @brief Process multiple AES blocks in parallel using AES-NI instructions.
 *
 * @param in Input data buffer (size: blocks * AES_BLOCK_SIZE bytes)
 * @param out Output data buffer (size: blocks * AES_BLOCK_SIZE bytes)
 * @param roundKeys Round keys as generated by the key expansion
 * @param blocks Number of 16-byte blocks to process
 * @param nr Number of rounds (10, 12, or 14)
 * @param encrypt Non-zero for encryption, zero for decryption
 */
#define INNER_LOOP(SUFFIX) \
	while (i + 8 <= blocks) \
	{ \
		process8Blocks##SUFFIX(in + i * AES_BLOCK_SIZE, out + i * AES_BLOCK_SIZE, rk, encrypt); \
		i += 8; \
	} \
	while (i < blocks) \
	{ \
		__m128i	d = _mm_loadu_si128((const __m128i *)(in + i * AES_BLOCK_SIZE)); \
		processBlock##SUFFIX(&d, rk, encrypt); \
		_mm_storeu_si128((__m128i *)(out + i * AES_BLOCK_SIZE), d); \
		i++; \
	}

__attribute__((target("aes")))
void	aesProcessBlocksX86(const uint8_t	*in,
							uint8_t			*out,
							const uint32_t	*roundKeys,
							size_t			blocks,
							int				nr,
							int				encrypt)
{
	__m128i	rk[AES_MAX_ROUNDS + 1];
	size_t	i;

	prepareKeys(rk, roundKeys, nr, encrypt);
	i = 0;
	switch (nr)
	{
		case AES_ROUNDS_128: INNER_LOOP(128) break;
		case AES_ROUNDS_192: INNER_LOOP(192) break;
		default: INNER_LOOP(256) break;
	}
}

#endif /* HAJCRYPT_SMALL_FOOTPRINT */

#endif /* AES_USE_AESNI */
