#include "../../../includes/cipher/aes.h"

#if defined(__aarch64__)
#include <arm_neon.h>

/*  ---------- Round primitives - single block ---------- */

/* Middle round: SubBytes + ShiftRows + MixColumns + AddRoundKey */
#define RE(d, rk, r)  (d) = vaesmcq_u8(vaeseq_u8((d), (rk)[r]))
#define RD(d, rk, r)  (d) = vaesimcq_u8(vaesdq_u8((d), (rk)[r]))

/* Final round: SubBytes + ShiftRows + AddRoundKey (no MixColumns) */
#define FE(d, rk, nr) (d) = veorq_u8(vaeseq_u8((d), (rk)[(nr) - 1]), (rk)[nr])
#define FD(d, rk, nr) (d) = veorq_u8(vaesdq_u8((d), (rk)[(nr) - 1]), (rk)[nr])

/**
 * @brief Prepare round keys for AES instructions.
 *
 * The AES instructions expect the round keys in a specific format:
 * - Each round key is loaded as a 128-bit vector, with bytes in reverse order.
 * - For decryption, the middle round keys (1..nr-1) must be transformed with vaesimcq_u8.
 *
 * @param rk Output array of round keys in NEON format (size: AES_MAX_ROUNDS + 1)
 * @param roundKeys Input round keys as generated by the key expansion
 * @param nr Number of rounds (10, 12, or 14)
 * @param encrypt Non-zero for encryption, zero for decryption
 */
__attribute__((target("aes"), always_inline))
static inline void	prepareKeys(uint8x16_t		*rk,
								const uint32_t	*roundKeys,
								int				nr,
								int				encrypt)
{
	uint8x16_t	orig[AES_MAX_ROUNDS + 1];
	int			i;

	for (i = 0; i <= nr; i++)
		orig[i] = vrev32q_u8(vld1q_u8((const uint8_t *)&roundKeys[i * 4]));
	if (encrypt)
	{
		for (i = 0; i <= nr; i++)
			rk[i] = orig[i];
	}
	else
	{
		rk[0] = orig[nr];
		for (i = 1; i < nr; i++)
			rk[i] = vaesimcq_u8(orig[nr - i]);
		rk[nr] = orig[0];
	}
}

/**
 * HAJCRYPT_SMALL_FOOTPRINT
 *   Defined	-> one generic implementation, runtime loop, ~1.5 KB object, 1373 MB/s aes-128-ecb on pi 5
 *   Undefined	-> three fully unrolled specialisations, ~15-20 KB object, 1435 MB/s aes-128-ecb on pi 5
 */
#ifdef HAJCRYPT_SMALL_FOOTPRINT

/* ---------- Small: generic 8-block function, loop not unrolled ---------- */

__attribute__((target("aes")))
static void	process8BlocksGeneric(const uint8_t		*in,
								  uint8_t			*out,
								  const uint8x16_t	*rk,
								  int				nr,
								  int				encrypt)
{
	uint8x16_t	d0, d1, d2, d3, d4, d5, d6, d7;
	int			r;

	d0 = vld1q_u8(in +   0);					d1 = vld1q_u8(in +  AES_BLOCK_SIZE);
	d2 = vld1q_u8(in +  AES_BLOCK_SIZE * 2);	d3 = vld1q_u8(in +  AES_BLOCK_SIZE * 3);
	d4 = vld1q_u8(in +  AES_BLOCK_SIZE * 4);	d5 = vld1q_u8(in +  AES_BLOCK_SIZE * 5);
	d6 = vld1q_u8(in +  AES_BLOCK_SIZE * 6);	d7 = vld1q_u8(in +  AES_BLOCK_SIZE * 7);
	if (encrypt)
	{
		for (r = 0; r < nr - 1; r++)
		{
			RE(d0, rk, r); RE(d1, rk, r); RE(d2, rk, r); RE(d3, rk, r);
			RE(d4, rk, r); RE(d5, rk, r); RE(d6, rk, r); RE(d7, rk, r);
		}
		FE(d0, rk, nr); FE(d1, rk, nr); FE(d2, rk, nr); FE(d3, rk, nr);
		FE(d4, rk, nr); FE(d5, rk, nr); FE(d6, rk, nr); FE(d7, rk, nr);
	}
	else
	{
		for (r = 0; r < nr - 1; r++)
		{
			RD(d0, rk, r); RD(d1, rk, r); RD(d2, rk, r); RD(d3, rk, r);
			RD(d4, rk, r); RD(d5, rk, r); RD(d6, rk, r); RD(d7, rk, r);
		}
		FD(d0, rk, nr); FD(d1, rk, nr); FD(d2, rk, nr); FD(d3, rk, nr);
		FD(d4, rk, nr); FD(d5, rk, nr); FD(d6, rk, nr); FD(d7, rk, nr);
	}
	vst1q_u8(out +   0, d0);					vst1q_u8(out +  AES_BLOCK_SIZE, d1);
	vst1q_u8(out +  AES_BLOCK_SIZE * 2, d2);	vst1q_u8(out +  AES_BLOCK_SIZE * 3, d3);
	vst1q_u8(out +  AES_BLOCK_SIZE * 4, d4);	vst1q_u8(out +  AES_BLOCK_SIZE * 5, d5);
	vst1q_u8(out +  AES_BLOCK_SIZE * 6, d6);	vst1q_u8(out +  AES_BLOCK_SIZE * 7, d7);
}

__attribute__((target("aes")))
static void	processSingleBlockGeneric(uint8x16_t		*d,
									  const uint8x16_t	*rk,
									  int				nr,
									  int				encrypt)
{
	int	r;

	if (encrypt)
	{
		for (r = 0; r < nr - 1; r++)
			RE(*d, rk, r);
		FE(*d, rk, nr);
	}
	else
	{
		for (r = 0; r < nr - 1; r++)
			RD(*d, rk, r);
		FD(*d, rk, nr);
	}
}

__attribute__((target("aes")))
void	aesProcessBlocksNeon(const uint8_t			*in,
								  uint8_t			*out,
								  const uint32_t	*roundKeys,
								  size_t			blocks,
								  int				nr,
								  int				encrypt)
{
	uint8x16_t	rk[AES_MAX_ROUNDS + 1];
	uint8x16_t	d;
	size_t		i;

	prepareKeys(rk, roundKeys, nr, encrypt);
	i = 0;
	while (i + 8 <= blocks)
	{
		process8BlocksGeneric(in + i * AES_BLOCK_SIZE, out + i * AES_BLOCK_SIZE, rk, nr, encrypt);
		i += 8;
	}
	while (i < blocks)
	{
		d = vld1q_u8(in + i * AES_BLOCK_SIZE);
		processSingleBlockGeneric(&d, rk, nr, encrypt);
		vst1q_u8(out + i * AES_BLOCK_SIZE, d);
		i++;
	}
}

#else /* !HAJCRYPT_SMALL_FOOTPRINT - fully unrolled, maximum performance */

/* ---------- Round primitives - 8 blocks in parallel ---------- */

#define R8E(rk, r) \
	RE(d0, rk, r); RE(d1, rk, r); RE(d2, rk, r); RE(d3, rk, r); \
	RE(d4, rk, r); RE(d5, rk, r); RE(d6, rk, r); RE(d7, rk, r)

#define R8D(rk, r) \
	RD(d0, rk, r); RD(d1, rk, r); RD(d2, rk, r); RD(d3, rk, r); \
	RD(d4, rk, r); RD(d5, rk, r); RD(d6, rk, r); RD(d7, rk, r)

#define F8E(rk, nr) \
	FE(d0, rk, nr); FE(d1, rk, nr); FE(d2, rk, nr); FE(d3, rk, nr); \
	FE(d4, rk, nr); FE(d5, rk, nr); FE(d6, rk, nr); FE(d7, rk, nr)

#define F8D(rk, nr) \
	FD(d0, rk, nr); FD(d1, rk, nr); FD(d2, rk, nr); FD(d3, rk, nr); \
	FD(d4, rk, nr); FD(d5, rk, nr); FD(d6, rk, nr); FD(d7, rk, nr)

/* ---------- Fully unrolled round sequences per key size ---------- */

/* AES-128 : nr=10 - 9 middle rounds (0..8) + final */
#define UNROLL1_ENC_10(d, rk) \
	RE(d,rk,0); RE(d,rk,1); RE(d,rk,2); RE(d,rk,3); RE(d,rk,4); \
	RE(d,rk,5); RE(d,rk,6); RE(d,rk,7); RE(d,rk,8); FE(d,rk,10)

#define UNROLL1_DEC_10(d, rk) \
	RD(d,rk,0); RD(d,rk,1); RD(d,rk,2); RD(d,rk,3); RD(d,rk,4); \
	RD(d,rk,5); RD(d,rk,6); RD(d,rk,7); RD(d,rk,8); FD(d,rk,10)

#define UNROLL8_ENC_10(rk) \
	R8E(rk,0); R8E(rk,1); R8E(rk,2); R8E(rk,3); R8E(rk,4); \
	R8E(rk,5); R8E(rk,6); R8E(rk,7); R8E(rk,8); F8E(rk,10)

#define UNROLL8_DEC_10(rk) \
	R8D(rk,0); R8D(rk,1); R8D(rk,2); R8D(rk,3); R8D(rk,4); \
	R8D(rk,5); R8D(rk,6); R8D(rk,7); R8D(rk,8); F8D(rk,10)

/* AES-192 : nr=12 - 11 middle rounds (0..10) + final */
#define UNROLL1_ENC_12(d, rk) \
	RE(d,rk,0); RE(d,rk,1); RE(d,rk,2);  RE(d,rk,3);  RE(d,rk,4); \
	RE(d,rk,5); RE(d,rk,6); RE(d,rk,7);  RE(d,rk,8);  RE(d,rk,9); \
	RE(d,rk,10); FE(d,rk,12)

#define UNROLL1_DEC_12(d, rk) \
	RD(d,rk,0); RD(d,rk,1); RD(d,rk,2);  RD(d,rk,3);  RD(d,rk,4); \
	RD(d,rk,5); RD(d,rk,6); RD(d,rk,7);  RD(d,rk,8);  RD(d,rk,9); \
	RD(d,rk,10); FD(d,rk,12)

#define UNROLL8_ENC_12(rk) \
	R8E(rk,0); R8E(rk,1); R8E(rk,2);  R8E(rk,3);  R8E(rk,4); \
	R8E(rk,5); R8E(rk,6); R8E(rk,7);  R8E(rk,8);  R8E(rk,9); \
	R8E(rk,10); F8E(rk,12)

#define UNROLL8_DEC_12(rk) \
	R8D(rk,0); R8D(rk,1); R8D(rk,2);  R8D(rk,3);  R8D(rk,4); \
	R8D(rk,5); R8D(rk,6); R8D(rk,7);  R8D(rk,8);  R8D(rk,9); \
	R8D(rk,10); F8D(rk,12)

/* AES-256 : nr=14 - 13 middle rounds (0..12) + final */
#define UNROLL1_ENC_14(d, rk) \
	RE(d,rk,0);  RE(d,rk,1);  RE(d,rk,2);  RE(d,rk,3);  RE(d,rk,4); \
	RE(d,rk,5);  RE(d,rk,6);  RE(d,rk,7);  RE(d,rk,8);  RE(d,rk,9); \
	RE(d,rk,10); RE(d,rk,11); RE(d,rk,12); FE(d,rk,14)

#define UNROLL1_DEC_14(d, rk) \
	RD(d,rk,0);  RD(d,rk,1);  RD(d,rk,2);  RD(d,rk,3);  RD(d,rk,4); \
	RD(d,rk,5);  RD(d,rk,6);  RD(d,rk,7);  RD(d,rk,8);  RD(d,rk,9); \
	RD(d,rk,10); RD(d,rk,11); RD(d,rk,12); FD(d,rk,14)

#define UNROLL8_ENC_14(rk) \
	R8E(rk,0);  R8E(rk,1);  R8E(rk,2);  R8E(rk,3);  R8E(rk,4); \
	R8E(rk,5);  R8E(rk,6);  R8E(rk,7);  R8E(rk,8);  R8E(rk,9); \
	R8E(rk,10); R8E(rk,11); R8E(rk,12); F8E(rk,14)

#define UNROLL8_DEC_14(rk) \
	R8D(rk,0);  R8D(rk,1);  R8D(rk,2);  R8D(rk,3);  R8D(rk,4); \
	R8D(rk,5);  R8D(rk,6);  R8D(rk,7);  R8D(rk,8);  R8D(rk,9); \
	R8D(rk,10); R8D(rk,11); R8D(rk,12); F8D(rk,14)

/**
 * @brief Define AES functions for a specific key size.
 * @param NR Number of rounds
 * @param SUFFIX Suffix for function names
 */
#define DEFINE_AES_FUNCS(NR, SUFFIX) \
\
__attribute__((target("aes"), always_inline)) \
static inline void	processBlock##SUFFIX( \
	uint8x16_t *data, const uint8x16_t *rk, int encrypt) \
{ \
	if (encrypt) { UNROLL1_ENC_##NR(*data, rk); } \
	else         { UNROLL1_DEC_##NR(*data, rk); } \
} \
\
__attribute__((target("aes"), always_inline)) \
static inline void	process8Blocks##SUFFIX( \
	const uint8_t *in, uint8_t *out, \
	const uint8x16_t *rk, int encrypt) \
{ \
	uint8x16_t	d0 = vld1q_u8(in +   0); \
	uint8x16_t	d1 = vld1q_u8(in +  AES_BLOCK_SIZE); \
	uint8x16_t	d2 = vld1q_u8(in +  AES_BLOCK_SIZE * 2); \
	uint8x16_t	d3 = vld1q_u8(in +  AES_BLOCK_SIZE * 3); \
	uint8x16_t	d4 = vld1q_u8(in +  AES_BLOCK_SIZE * 4); \
	uint8x16_t	d5 = vld1q_u8(in +  AES_BLOCK_SIZE * 5); \
	uint8x16_t	d6 = vld1q_u8(in +  AES_BLOCK_SIZE * 6); \
	uint8x16_t	d7 = vld1q_u8(in + AES_BLOCK_SIZE * 7); \
	if (encrypt) { UNROLL8_ENC_##NR(rk); } \
	else         { UNROLL8_DEC_##NR(rk); } \
	vst1q_u8(out +   0, d0);					vst1q_u8(out +  AES_BLOCK_SIZE, d1); \
	vst1q_u8(out +  AES_BLOCK_SIZE * 2, d2);	vst1q_u8(out +  AES_BLOCK_SIZE * 3, d3); \
	vst1q_u8(out +  AES_BLOCK_SIZE * 4, d4);	vst1q_u8(out +  AES_BLOCK_SIZE * 5, d5); \
	vst1q_u8(out +  AES_BLOCK_SIZE * 6, d6);	vst1q_u8(out +  AES_BLOCK_SIZE * 7, d7); \
}

/* Instantiate the three key-size variants */
DEFINE_AES_FUNCS(10, 128)
DEFINE_AES_FUNCS(12, 192)
DEFINE_AES_FUNCS(14, 256)

/**
 * @brief Process multiple AES blocks in parallel using NEON instructions.
 *
 * This function processes the input data in chunks of 8 blocks (128 bytes) when possible,
 * and falls back to single-block processing for any remaining blocks.
 *
 * @param in Input data buffer (size: blocks * AES_BLOCK_SIZE bytes)
 * @param out Output data buffer (size: blocks * AES_BLOCK_SIZE bytes)
 * @param roundKeys Round keys as generated by the key expansion
 * @param blocks Number of 16-byte blocks to process
 * @param nr Number of rounds (10, 12, or 14)
 * @param encrypt Non-zero for encryption, zero for decryption
 */
#define INNER_LOOP(SUFFIX) \
	while (i + 8 <= blocks) \
	{ \
		process8Blocks##SUFFIX(in + i * AES_BLOCK_SIZE, out + i * AES_BLOCK_SIZE, rk, encrypt); \
		i += 8; \
	} \
	while (i < blocks) \
	{ \
		uint8x16_t	d = vld1q_u8(in + i * AES_BLOCK_SIZE); \
		processBlock##SUFFIX(&d, rk, encrypt); \
		vst1q_u8(out + i * AES_BLOCK_SIZE, d); \
		i++; \
	}

__attribute__((target("aes")))
void	aesProcessBlocksNeon(const uint8_t *in, uint8_t *out,
							 const uint32_t *roundKeys,
							 size_t blocks, int nr, int encrypt)
{
	uint8x16_t	rk[AES_MAX_ROUNDS + 1];
	size_t		i;

	prepareKeys(rk, roundKeys, nr, encrypt);
	i = 0;
	switch (nr)
	{
		case AES_ROUNDS_128: INNER_LOOP(128) break;
		case AES_ROUNDS_192: INNER_LOOP(192) break;
		default: INNER_LOOP(256) break;
	}
}

#endif /* HAJCRYPT_SMALL_FOOTPRINT */
#endif /* __aarch64__ */
